In [1]:
import numpy as np

#### Calculate the profitt/Loss for given data
 - Revenue
|      | 2018| 2019|2020
| -----| --- | --- |--- |
|Iphone| 180 | 200 |220 |
|Ipad  | 24  | 36  | 40 |
|Mac   | 12  | 18  | 20 |

- Expenses


|      | 2018| 2019|2020
| -----| --- | --- |--- |
|Iphone| 80  | 90  |100 |
|Ipad  | 10  | 16  | 20 |
|Mac   | 8   | 10  | 20 |


In [2]:
### Represent the revenue and expenses as numpy array
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expense = np.array([[80,90,100],[10,16,20],[8,10,20]])

In [3]:
profit = revenue - expense
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,   0]])

#### Calculate total sales from units and price per unit using matrix multiplication
- Price
|      | Iphone| Ipad|Mac|
| -----| --- | --- |--- |
|price per unit| 1000 | 400 |1200 |

- Total Unit

|      | 2018| 2019|2020
| -----| --- | --- |--- |
|Iphone| 30  | 40  |50 |
|Ipad  | 5  | 10  | 15 |
|Mac   | 2   | 5  | 7 |

- This requires a dot product, which means row*column multiplication to calculate the total sales per year

In [4]:
price = np.array([1000,400,1200])
total_unit = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [5]:
total_sales = np.dot(price,total_unit)

In [6]:
total_sales

array([34400, 50000, 64400])

#### Exercise: Matrix Math
1. Below is some indian companies revenues in US dollars. Using numpy can you convert this into Indian rupees? 1 USD = 75 INR

![](revenue_usd.jpeg)

In [14]:
revenue_usd = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
USD = 75
Revenue_INR = np.multiply(revenue_usd,USD)
Revenue_INR

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])


2. Divine flowers is a flower shop that sells different type of flowers. Below is the table showing how many flowers of each type they sold in different months. Also given are the prices of one flower each. Using this find out their total sales in every month.

![](flowers.jpeg)

In [15]:
flower_sale = np.array([[50,60,25],[10,13,5],[40,70,52]])
price_flower = np.array([20,30,15])
total_sales = np.dot(price_flower,flower_sale)
total_sales

array([1900, 2640, 1430])

3. Here is some matrix exercise from mathisfun.com. Please click on a link below and do the exercise.

[Click me for matrix exercise](https://www.mathopolis.com/questions/q.html?id=714&t=mif&qs=714_715_716_717_2394_2395_2397_2396_8473_8474_8475_8476&site=1&ref=2f616c67656272612f6d61747269782d6d756c7469706c79696e672e68746d6c&title=486f7720746f204d756c7469706c79204d61747269636573)
